# Generated by Django 2.2.16 on 2022-08-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220816_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
