# Generated by Django 2.2.16 on 2022-08-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220817_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.FloatField(db_index=True, null=True, unique=True),
        ),
    ]
