# Generated by Django 2.2.16 on 2022-08-21 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220819_0143'),
        ('users', '0007_auto_20220819_1446'),
    ]

    operations = [
    ]
