# Generated by Django 2.2.16 on 2022-08-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220822_2305'),
        ('users', '0008_auto_20220822_0822'),
    ]

    operations = [
    ]
