# Generated by Django 2.2.16 on 2022-08-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20220822_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.IntegerField(db_index=True, max_length=256, null=True, unique=True),
        ),
    ]
