# Generated by Django 2.2.16 on 2022-08-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220819_1816'),
        ('reviews', '0006_auto_20220819_1615'),
    ]

    operations = [
    ]
